### ISSUE TITLE
还是不能自动获取大王卡申请地址的接口啊

### ISSUE THREAD

**Issue by Zayia** [KirosHan/numsieve#6]
大王卡申请地址是这个
https://m.10010.com/queen/tencent/onlineGo.html?param=P2guLDMlC7IabUFK610VX7mVrii3M9HzuHgOSj%2F%2BDDTg1tXhEnwI1V4DFw58SC5wTr7oyiaISRDvDajYONVj%2FT2svyHlJEFYp%2B%2FxeUP8s3Wc9%2FmcJTtVqRxmM2QmF4YfFJvTcL4wK56mG%2F5Vmydznxa0KuMrqe9yBY3QaleiZB%2FcMhUAvKQKsDESl2CGxqy4nUbvDXDjl%2B6TbaFmiy1KjuPkKX7dTwFOoGsrC0BJsDZ24hNwhM%2FUGHmfPGWrcUPX&audience=172716
用自带的抓包工具抓不到
只能用别的抓包工具

**Comment by qwertccc** [comment]
要是能支持大王卡就好了哈哈

**Comment by Zayia** [comment]
支持的，不过需要自己用别的抓包工具来抓包

**Comment by KirosHan** [comment]
最近有点忙    过一两天更新     现在可以先用fiddler4来抓一下链接

**Comment by qwertccc** [comment]
https://m.10010.com/NumApp/NumberCenter/qryNum?callback=jsonp_queryMoreNums&provinceCode=11&cityCode=110&monthFeeLimit=0&groupKey=85236889&searchCategory=3&net=01&amounts=200&codeTypeCode=&searchValue=&qryType=02&goodsNet=4&_=1525675484875


大王卡的地址，直接扫就行了，这里是北京的，cityCode=110，别的城市是多少自己找找试试，我没看

**Comment by qwertccc** [comment]
都是垃圾号，我。。。开始是想买一张的，现在犹豫了我擦

**Comment by Zayia** [comment]
地址我已经找到了，就是来反馈一下找到地址不能自动获取的问题
话说前几天是可以扫到一些四拖一的号码
这几天不行了
